import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff'
  },
   headContainer: {
    marginTop: 50,
    marginLeft: 10,
    marginRight: 10,
    flexDirection: 'row', 
    justifyContent: 'space-between', 
    alignItems: 'center',
    width: width - 20, 
  },
  headline: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  listContainer: {
    flex: 1,
    paddingHorizontal: 15,
  },
  cardContainer: {
    backgroundColor: '#F4DEB3',
    borderRadius: 20,
    width: '90%',
    paddingVertical: 15,
    paddingHorizontal: 15,
    marginVertical: 10,
    marginHorizontal: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 4,
    justifyContent: 'space-between', 
  },
  textContainer: {
    flex: 1,
    marginRight: 10,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333333', 
  },
  cardDetails: {
    fontSize: 14,
    color: '#666666',
  },
  buttonsContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginRight: 10,
  },
  contentContainer: {
    flex: 1,
    marginLeft: 5,
    marginRight: 5,
    padding: 5,
    flexDirection: 'column', 
    justifyContent: 'flex-start', 
  },
  //media
  imageWrapper: {
    alignItems: 'center',
  },
  image: {
    width: width * 0.9, 
    height: height * 0.5, 
  },
  //buttons
   homeButton: {
    backgroundColor: '#a0f0aa',
    borderColor: '#006400',  
    borderWidth: 1, 
    borderRadius: 25, 
    paddingVertical: 10, 
    paddingHorizontal: 20,  
    shadowColor: '#000', 
    shadowOffset: { width: 0, height: 4 }, 
    shadowOpacity: 0.2, 
    shadowRadius: 6, 
    elevation: 5,
    alignItems: 'center',  
  },
  buttonText: {
    fontSize: 15,
    fontWeight: 'bold',
    color: '#004d00',
  },
  button: {
    backgroundColor: '#a0f0aa',
    borderColor: '#006400',  
    borderWidth: 1, 
    borderRadius: 25, 
    paddingVertical: 10, 
    paddingHorizontal: 20,  
    shadowColor: '#000', 
    shadowOffset: { width: 0, height: 4 }, 
    shadowOpacity: 0.2, 
    shadowRadius: 6, 
    elevation: 5,
    alignItems: 'center',
  },
  buttonWrapper: {
    alignItems: 'center',
  },
  deleteButton: {
    backgroundColor: '#8B0000',
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    marginTop: 10,
  },
  deleteButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: 'bold',
  },
  addButton: {
    backgroundColor: '#ccffcc',
    paddingVertical: 10,
    paddingHorizontal: 25,
    borderRadius: 20,
   // borderWidth:1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
    marginTop: 10,
    alignItems: 'center',
  },
  addButtonContainer: {
    marginVertical: 15,
    marginHorizontal: 60,
  },
  addButtonText: {
    color: '#000000',
    fontSize: 18,
    fontWeight: 'bold',
  },
  cancelButton: {
    backgroundColor: '#fee588',
    paddingVertical: 10,
    paddingHorizontal: 25,
    borderRadius: 20,
   // borderWidth:1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
    marginTop: 10,
    alignItems: 'center',
  },
  cancelButtonText: {
    color: '#000000',
    fontSize: 18,
  },
  detailsButton: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 20,
    //borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    marginTop: 10,
  },
  detailsButtonText: {
    color: '#4B3F00',
    fontSize: 14,
    fontWeight: 'bold',
  },
  updateButton: {
    backgroundColor: '#D6DAC8',
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 20,
    //borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 3,
    marginTop: 10,
  }
});

export default styles;
